import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>postcards from the summer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          postcards from the summer
        </h1>

        <p className={styles.description}>
          a collection of creative pieces and curated works
        </p>
      </main>
    </div>
  )
}
